lift_txd = engineLoadTXD("Data/vehiclelift.txd")
engineImportTXD(lift_txd,2597)
hoist_dff = engineLoadDFF("Data/hoist.dff",2597)
engineReplaceModel(hoist_dff,2597)
hoist_col = engineLoadCOL("Data/hoist.col")
engineReplaceCOL(hoist_col,2597)
engineImportTXD(lift_txd,2231)
ramp_dff = engineLoadDFF("Data/ramp.dff",2231)
engineReplaceModel(ramp_dff,2231)
ramp_col = engineLoadCOL("Data/ramp.col")
engineReplaceCOL(ramp_col,2231)
engineImportTXD(engineLoadTXD("Data/garage1.txd"),11389)
engineImportTXD(engineLoadTXD("Data/garage2.txd"),11387)
