addEventHandler("onClientResourceStart", resourceRoot, function()
  shader = dxCreateShader("sidewalk/shader.fx")
  terrain = dxCreateTexture("sidewalk/38.jpg")
  dxSetShaderValue(shader, "gTexture", terrain)
  engineApplyShaderToWorldTexture(shader, "sjmhoodlawn41")
  engineApplyShaderToWorldTexture(shader, "plaintarmac1")
  engineApplyShaderToWorldTexture(shader, "dockpave_256")
  engineApplyShaderToWorldTexture(shader, "ws_nicepave")
  engineApplyShaderToWorldTexture(shader, "sidelatino1_LAe")
  engineApplyShaderToWorldTexture(shader, "LAroad_offroad1")
  engineApplyShaderToWorldTexture(shader, "kbpavement_test")
  engineApplyShaderToWorldTexture(shader, "vegaspavement2_256")
  engineApplyShaderToWorldTexture(shader, "blendpavement2b_256")
  engineApplyShaderToWorldTexture(shader, "vegasdirtypave2_256")
  engineApplyShaderToWorldTexture(shader, "blendpavement2b_256")
  engineApplyShaderToWorldTexture(shader, "pavebsand256")
  engineApplyShaderToWorldTexture(shader, "sidewalk4_LAe")
  engineApplyShaderToWorldTexture(shader, "sjmhoodlawn42")
  engineApplyShaderToWorldTexture(shader, "sidewgrass2")
  engineApplyShaderToWorldTexture(shader, "sidewgrass_fuked")
  engineApplyShaderToWorldTexture(shader, "sidewgrass5")
  engineApplyShaderToWorldTexture(shader, "sidewgrass3")
  engineApplyShaderToWorldTexture(shader, "sidewgrass1")
  engineApplyShaderToWorldTexture(shader, "starpave_law")
  engineApplyShaderToWorldTexture(shader, "starpaveb_law")
  engineApplyShaderToWorldTexture(shader, "sf_pave2")
  engineApplyShaderToWorldTexture(shader, "sf_pave6")
  engineApplyShaderToWorldTexture(shader, "sf_pave3")
  engineApplyShaderToWorldTexture(shader, "sf_pave4")
  engineApplyShaderToWorldTexture(shader, "sf_pave5")
  engineApplyShaderToWorldTexture(shader, "craproad5_LAe")
  engineApplyShaderToWorldTexture(shader, "craproad6_LAe")
  engineApplyShaderToWorldTexture(shader, "LAroad_centre1")
  engineApplyShaderToWorldTexture(shader, "vegasdirtypave1_256")
  engineApplyShaderToWorldTexture(shader, "ws_nicepave")
  engineApplyShaderToWorldTexture(shader, "nicepavegras_LA")
  engineApplyShaderToWorldTexture(shader, "brickred2")
  engineApplyShaderToWorldTexture(shader, "indund_64")
  engineApplyShaderToWorldTexture(shader, "kbpavementblend")
  engineApplyShaderToWorldTexture(shader, "cos_hiwayins_256")
  engineApplyShaderToWorldTexture(shader, "sjmhoodlawn42B")
  engineApplyShaderToWorldTexture(shader, "hiwayinside5_256")
  engineApplyShaderToWorldTexture(shader, "hiwayinside2_256")
  engineApplyShaderToWorldTexture(shader, "hiwayinside_256")
  engineApplyShaderToWorldTexture(shader, "hiwayinsideblend3_256")
  engineApplyShaderToWorldTexture(shader, "pavebsand256blueblend")
  engineApplyShaderToWorldTexture(shader, "hiwayinsideblend2_256")
  engineApplyShaderToWorldTexture(shader, "hiwayinsideblend1_256")
  engineApplyShaderToWorldTexture(shader, "sl_pavebutt1")
  engineApplyShaderToWorldTexture(shader, "sjmscorclawn")
  engineApplyShaderToWorldTexture(shader, "sjmhoodlawn4")
  engineApplyShaderToWorldTexture(shader, "sl_pavebutt2")
  engineApplyShaderToWorldTexture(shader, "blendpavement2_256")
  engineApplyShaderToWorldTexture(shader, "vegasdirtypaveblend2")
  engineApplyShaderToWorldTexture(shader, "vgsroadirt2_256")
  engineApplyShaderToWorldTexture(shader, "vegasdirtypaveblend1")
end
)
addEventHandler("onClientResourceStart", resourceRoot, function()
  shader = dxCreateShader("sidewalk/shader.fx")
  terrain = dxCreateTexture("sidewalk/38.jpg")
  dxSetShaderValue(shader, "gTexture", terrain)
  engineApplyShaderToWorldTexture(shader, "sjmhoodlawn41")
  engineApplyShaderToWorldTexture(shader, "plaintarmac1")
  engineApplyShaderToWorldTexture(shader, "Newpavement")
  engineApplyShaderToWorldTexture(shader, "backalley1_LAe")
  engineApplyShaderToWorldTexture(shader, "craproad6_LAe")
end
)
