addEvent("TheftSound", true)
addEventHandler("TheftSound", getRootElement(), function(find)
    local Sound = playSound3D("Files/brrring.mp3", 0, 0, 0, false)
    setSoundMaxDistance(Sound, 20)
    attachElements(Sound, find)
end)

addEvent("AntiSound", true)
addEventHandler("AntiSound", getRootElement(), function(thePlayer)
    local Sound = playSound3D("Files/damn.mp3", 0, 0, 0, false)
    setSoundMaxDistance(Sound, 20)
    attachElements(Sound, thePlayer)
end)

addEvent("TheftDoneSound", true)
addEventHandler("TheftDoneSound", getRootElement(), function(find)
    local Sound = playSound3D("Files/giggles.ogg", 0, 0, 0, false)
    setSoundMaxDistance(Sound, 20)
    attachElements(Sound, find)
end)