function vhandling ( )
   for _,v in pairs(getElementsByType("vehicle")) do
      setVehicleHandling (v, "collisionDamageMultiplier",0.1)
      if getElementModel(v) == 551 then -------------- vehicle Id
        setVehicleHandling (v, "mass", 3000.0)
        setVehicleHandling(v, "turnMass", 3000)
        setVehicleHandling(v, "dragCoeff", 0.1 )
        setVehicleHandling(v, "centerOfMass", { 0.0,0.06,-0.09 } )
        setVehicleHandling(v, "percentSubmerged", 90)
        setVehicleHandling(v, "tractionMultiplier", 1.4)
        setVehicleHandling(v, "tractionLoss", 1.3)
        setVehicleHandling(v, "tractionBias", 0.49)
        setVehicleHandling(v, "numberOfGears", 5)
        setVehicleHandling(v, "acceleration", 10)
        setVehicleHandling(v, "maxVelocity", 330)
        setVehicleHandling(v, "engineAcceleration", 40.0 )
        setVehicleHandling(v, "engineInertia", 10.0)
        setVehicleHandling(v, "driveType", "awd")
        setVehicleHandling(v, "engineType", "petrol")
        setVehicleHandling(v, "brakeDeceleration", 20.0)
        setVehicleHandling(v, "brakeBias", 0.30)
      end
         if getElementModel(v) == 400 then -------------- vehicle Id
         setVehicleHandling (v, "mass", 3000.0)
         setVehicleHandling(v, "turnMass", 3000)
         setVehicleHandling(v, "dragCoeff", 0.1 )
         setVehicleHandling(v, "centerOfMass", { 0.0,0.06,-0.09 } )
         setVehicleHandling(v, "percentSubmerged", 90)
         setVehicleHandling(v, "tractionMultiplier", 1.4)
         setVehicleHandling(v, "tractionLoss", 1.3)
         setVehicleHandling(v, "tractionBias", 0.49)
         setVehicleHandling(v, "numberOfGears", 5)
         setVehicleHandling(v, "maxVelocity", 260)
         setVehicleHandling(v, "engineAcceleration", 40.0 )
         setVehicleHandling(v, "engineInertia", 10.0)
         setVehicleHandling(v, "driveType", "awd")
         setVehicleHandling(v, "engineType", "petrol")
         setVehicleHandling(v, "brakeDeceleration", 20.0)
         setVehicleHandling(v, "brakeBias", 0.30)
         end
         if getElementModel(v) == 401 then -------------- vehicle Id
            setVehicleHandling (v, "mass", 3000.0)
            setVehicleHandling(v, "turnMass", 3000)
            setVehicleHandling(v, "dragCoeff", 0.1 )
            setVehicleHandling(v, "centerOfMass", { 0.0,0.06,-0.09 } )
            setVehicleHandling(v, "percentSubmerged", 90)
            setVehicleHandling(v, "tractionMultiplier", 1.4)
            setVehicleHandling(v, "tractionLoss", 1.3)
            setVehicleHandling(v, "tractionBias", 0.49)
            setVehicleHandling(v, "numberOfGears", 5)
            setVehicleHandling(v, "maxVelocity", 360)
            setVehicleHandling(v, "engineAcceleration", 40.0 )
            setVehicleHandling(v, "engineInertia", 10.0)
            setVehicleHandling(v, "driveType", "awd")
            setVehicleHandling(v, "engineType", "petrol")
            setVehicleHandling(v, "brakeDeceleration", 20.0)
            setVehicleHandling(v, "brakeBias", 0.30)
         end
      if getElementModel(v) == 603 then -------------- vehicle Id
         setVehicleHandling (v, "mass", 2600.0)
         setVehicleHandling(v, "turnMass", 2600)
         setVehicleHandling(v, "dragCoeff", 1.0 )
         setVehicleHandling(v, "centerOfMass", { 0.0,0.06,-0.09 } )
         setVehicleHandling(v, "percentSubmerged", 90)
         setVehicleHandling(v, "tractionMultiplier", 1.1)
         setVehicleHandling(v, "tractionLoss", 1.1)
         setVehicleHandling(v, "tractionBias", 0.49)
         setVehicleHandling(v, "numberOfGears", 5)
         setVehicleHandling(v, "maxVelocity", 190)
         setVehicleHandling(v, "engineAcceleration", 20.0 )
         setVehicleHandling(v, "engineInertia", 10.0)
         setVehicleHandling(v, "driveType", "awd")
         setVehicleHandling(v, "engineType", "petrol")
         setVehicleHandling(v, "brakeDeceleration", 20.0)
         setVehicleHandling(v, "brakeBias", 0.30)
      end
      if getElementModel(v) == 422 then -------------- vehicle Id
         setVehicleHandling (v, "mass", 3000.0)
         setVehicleHandling(v, "turnMass", 3000)
         setVehicleHandling(v, "dragCoeff", 1.0 )
         setVehicleHandling(v, "centerOfMass", { 0.0,0.06,-0.09 } )
         setVehicleHandling(v, "percentSubmerged", 90)
         setVehicleHandling(v, "tractionMultiplier", 1.3)
         setVehicleHandling(v, "tractionLoss", 1.3)
         setVehicleHandling(v, "tractionBias", 0.49)
         setVehicleHandling(v, "numberOfGears", 5)
         setVehicleHandling(v, "maxVelocity", 400)
         setVehicleHandling(v, "engineAcceleration", 40.0 )
         setVehicleHandling(v, "engineInertia", 10.0)
         setVehicleHandling(v, "driveType", "awd")
         setVehicleHandling(v, "engineType", "petrol")
         setVehicleHandling(v, "brakeDeceleration", 20.0)
         setVehicleHandling(v, "brakeBias", 0.30)
         setVehicleHandling(v, "suspensionForceLevel", 1)
         setVehicleHandling(v, "suspensionDamping", 0 )
      end
   end
end
addEventHandler ( "onPlayerVehicleEnter", getRootElement(), vhandling )
function setcarhp()
   for _,theVeh in ipairs (getElementsByType("vehicle")) do
      if getElementHealth(theVeh) >= 1000 then
         setElementHealth(theVeh,1300)
      end
   end
end
setTimer(setcarhp, 5000, 0)