local accSys = exports["Accounts-System"]
function createVehiclesForAcc(root)
	local car1 = getElementData(accSys:getPlayerAcc(root), "cModel")
	local car2 = getElementData(accSys:getPlayerAcc(root), "cModel_2")
	if car1 > 0 then
		local id = getElementData(accSys:getPlayerAcc(root), "cModel")
		local x = getElementData(accSys:getPlayerAcc(root), "cLocationx")
		local y = getElementData(accSys:getPlayerAcc(root), "cLocationy")
		local z = getElementData(accSys:getPlayerAcc(root), "cLocationz")
		local r1 = getElementData(accSys:getPlayerAcc(root), "cMod1")
		local g1 = getElementData(accSys:getPlayerAcc(root), "cMod3")
		local b1 = getElementData(accSys:getPlayerAcc(root), "cMod4")
		local r2 = getElementData(accSys:getPlayerAcc(root), "cMod5")
		local g2 = getElementData(accSys:getPlayerAcc(root), "cMod6")
		local b2 = getElementData(accSys:getPlayerAcc(root), "cMod7")
		local r3 = getElementData(accSys:getPlayerAcc(root), "cMod8")
		local g3 = getElementData(accSys:getPlayerAcc(root), "cMod9")
		local b3 = getElementData(accSys:getPlayerAcc(root), "cMod10")
		local rot = getElementData(accSys:getPlayerAcc(root), "cAngle")
		local pcar = createVehicle ( tonumber(id), tonumber(x), tonumber(y), tonumber(z))
		setElementRotation ( pcar, 0, 0, tonumber(rot) )
		setVehicleColor( pcar, r1, g1, b1, r2, g2, b2)
		local dscolor = setVehicleHeadLightColor ( pcar, r3, g3, b3 )
		setVehicleLocked ( pcar, true )
		local ownername =  getPlayerName(root)
		setElementData(pcar, "owner",ownername)
		local pelak = getElementData(accSys:getPlayerAcc(root), "cPlate")
       	setVehiclePlateText( pcar, pelak )
	end
	if car2 > 0 then
		local id = getElementData(accSys:getPlayerAcc(root), "cModel_2")
	    local x = getElementData(accSys:getPlayerAcc(root), "cLocationx_2")
		local y = getElementData(accSys:getPlayerAcc(root), "cLocationy_2")
		local z = getElementData(accSys:getPlayerAcc(root), "cLocationz_2")
		local r1 = getElementData(accSys:getPlayerAcc(root), "cMod1_2")
		local g1 = getElementData(accSys:getPlayerAcc(root), "cMod3_2")
		local b1 = getElementData(accSys:getPlayerAcc(root), "cMod4_2")
		local r2 = getElementData(accSys:getPlayerAcc(root), "cMod5_2")
		local g2 = getElementData(accSys:getPlayerAcc(root), "cMod6_2")
		local b2 = getElementData(accSys:getPlayerAcc(root), "cMod7_2")
		local r3 = getElementData(accSys:getPlayerAcc(root), "cMod8_2")
		local g3 = getElementData(accSys:getPlayerAcc(root), "cMod9_2")
		local b3 = getElementData(accSys:getPlayerAcc(root), "cMod10_2")
		local rot = getElementData(accSys:getPlayerAcc(root), "cAngle_2")
		local pcar = createVehicle ( tonumber(id), tonumber(x), tonumber(y), tonumber(z))
		setElementRotation ( pcar, 0, 0, tonumber(rot) )
		setVehicleColor( pcar, r1, g1, b1, r2, g2, b2)
		local dscolor = setVehicleHeadLightColor ( pcar, r3, g3, b3 )
		setVehicleLocked ( pcar, true )
		local ownername =  getPlayerName(root)
		setElementData(pcar, "owner",ownername)
		local pelak = getElementData(accSys:getPlayerAcc(root), "cPlate_2")
      	setVehiclePlateText( pcar, pelak )
		setElementRotation ( pcar, 0, 0, tonumber(rot) )
	end
end