function cancelanimbydownkey()
	triggerServerEvent("stopanim", getLocalPlayer(), getLocalPlayer() )
end
bindKey("aim_weapon","down",function()
	cancelanimbydownkey()
end)
bindKey("fire","down",function()
	cancelanimbydownkey()
end)
bindKey("next_weapon","down",function()
	cancelanimbydownkey()
end)
bindKey("jump","down",function()
	cancelanimbydownkey()
end)
bindKey("forwards","down",function()
	cancelanimbydownkey()
end)
bindKey("backwards","down",function()
	cancelanimbydownkey()
end)
bindKey("left","down",function()
	cancelanimbydownkey()
end)
bindKey("right","down",function()
	cancelanimbydownkey()
end)

